lib/stripe/utils/index.js
lib/stripe/utils/vat-rates.json

Fixed rates.

---

public/js/editors/libraries.js

Add Normalize.css to libraries list

---

lib/app.js
public/js/account/editor-settings.js

Add empty state property to jsbin for editor

---

lib/app.js

The properties `view engine` and `view` set here are set again a number of lines later, see: https://github.com/jsbin/jsbin/blob/master/lib/app.js#L154

Cleanup setters

---

public/css/style.css
public/css/upgrade.css
views/index.html

@slightlyoff commands. @remy obeys.

---

public/js/editors/libraries.js

Knockout 3.3.0 should be suggested by the dropdown

Updated Knockout to latest version

---

public/js/editors/libraries.js

This has been bugging me for a bit, so I thought I'd quit whining and do something about it.
Couldn't find `CONTRIBUTING.md` or the like, hope this all works out.

Update patch of Angular 1.3 & add Angular 1.4

---

public/js/editors/libraries.js

Add immutable data structures libs:
- Immutable 3.7.3
- mori 0.3.2

Add Immutable and mori to libraries

---

lib/handlers/bin.js
lib/routes.js
public/js/chrome/welcome-panel.js

The new start.js was circumventing the cname lookup - now it doesn't. Also trying to get rid of the constant unread blog post number in jsbin (when you switch domains between https and http).
Fixes #2431

fix: custom domain support

---

public/js/chrome/share.js

fix: embed url in share box

---

public/js/chrome/navigation.js
public/js/chrome/settings.js
public/js/editors/keycontrol.js

fix: settings saving on inline changes

---

public/custom/emberjs/default.html
public/js/editors/libraries.js

- Bumps ember version to 1.13.2 (current release)
- Bumps ember-data to 1.13.4 (current release)

Bump ember and ember-data versions

---

public/js/editors/libraries.js

can we update Kendo UI source code?

Clean up and Update Kendo UI

---

public/custom/emberjs/default.html
public/js/editors/libraries.js

- Bumps Ember to v1.13.4
- Bumps Ember Data to v1.13.5

Bump ember and ember data versions

---

public/js/editors/libraries.js

This adds support for [Ramda](http://ramdajs.com/), another functional programming library.

Add Ramda as an available library

---

public/custom/emberjs/default.html
public/js/editors/libraries.js

Bumps ember version to v1.13.5
https://github.com/emberjs/ember.js/releases/tag/v1.13.5

Bump ember version to v1.13.15

---

views/504.html

The original message was 145 characters long, 5 character over the limit (140).
This little edit puts the total length at 133 chars, 7 character less than 140.
..also yeah, the website's doing 504 to me.

Make the tweet fit into Twitter's character limit

---

lib/processors/index.js
public/js/editors/libraries.js
public/js/editors/panel.js
public/js/processors/processor.js
public/js/workers/cljs-worker.js

This PR replaces current ClojureScript support via server-side compiler with self-hosted version, [see](http://swannodette.github.io/2015/07/29/clojurescript-17/).

replace ClojureScript with self-hosted version

---

public/js/render/live.js

Fixes #2586
Props to @mikewest ❤

fix: allow alerts in the iframe again

---

public/js/editors/libraries.js

Fixes https://github.com/jsbin/jsbin/issues/2526 and https://github.com/jsbin/jsbin/issues/2511.

add moment (2.10.6 w & w/o locales)

---

public/js/editors/libraries.js

This should resolve #2612. Let me know if you have any thoughts. Thanks!

Add Velocity JS and UI Pack to libraries

---

public/custom/react/default.html
public/custom/react/default.js
public/js/editors/libraries.js

Tested locally. I kept React 0.13.3 since there are some API changes (e.g. `React` -> `ReactDOM`) and we seem to be keeping older versions of Angular.

Add React 0.14.3

---

public/js/runner/processor.js

Tested in Firefox 43.0.4, as was seeing reported behaviour.

fix issue #2651 by caching old methods and restoring them

---

public/js/editors/libraries.js

Update library to latest CDN version

Update video.js version

---

public/js/editors/libraries.js

Added RiotJS (http://riotjs.com/) to libraries list.

Added Riot to libraries list

---

public/js/editors/libraries.js

Added Ractive.js (http://www.ractivejs.org/) to Libraries list.

#2675 Added Ractive.js to Libraries list

---

public/js/editors/libraries.js

Fixes #2711 : Update the Vue library url to cdnjs

---

public/custom/react/default.html
public/js/editors/libraries.js

I also switched to the development (unminified) builds which give useful warnings which you typically want when building examples in a bin.

Update to React 15.1.0

---

public/js/editors/libraries.js

Added Bliss

---

public/js/editors/library.js

Insert code snippet for selected library at cursor location

---

public/js/editors/libraries.js

update moment (2.14.1 w & w/o locales)

---

emails/email-footer.html
emails/email-header.html
emails/new-customer-report.html
emails/new-customer-report.txt
lib/email/quick-send.js
lib/stripe/handlers/customer.subscription.created.js
lib/stripe/handlers/index.js
package.json
test/fixtures/customer.json
test/fixtures/customer.subscription.created.json
test/unit/lib/email.test.js
test/unit/lib/stripe/customer-subscription-created.test.js

And add report for new customers to help narrow down fraud abuse.
Also adds units tests using tap (my preferred method), but these aren't really running atm, just used for local testing.

fix: welcome email

---

public/js/editors/libraries.js

Commit history: https://github.com/ramda/ramda/compare/v0.20.1...v0.22.1
Upgrade guides for developers: https://github.com/ramda/ramda/issues?q=label%3A%22upgrade+guide%22

Update Ramda to 0.22.1

---

lib/handlers/bin.js
lib/routes.js
public/js/jsbin.js

@remy this should fix the problem, but please test it as I am not sure my local dev environment is completely up-to-date.

#2459 Fixed export to gist by adding github token to user settings

---

public/js/editors/libraries.js

update three from 72 -> 82

---

lib/db/sqlite.js

The arguments' type is Array, not Object.

:bug:fixed deletion bug while using sqlite

---

src/lib/makeIFrame.js

iframe permissions

---

public/js/runner/sandbox.js

Fixes chrome permissions for runner iframe

---

package-lock.json
package.json
src/components/Mirror.js
src/lib/CodeMirror/cmd-snippets.js
src/lib/CodeMirror/emmet.js

* Removed old emmet plugin that is deprecated not used anymore
* Loaded the proper emmet addon into codemirror
* Added the new emmet function to the existing snippet function, but only when the snippet doesn't exist

Added emmet to the tab key
