jsbin/jsbin

public/js/editors/libraries.js
This PR updates version of Bootstrap to recently released 3.3.2 version: 
http://blog.getbootstrap.com/2015/01/19/bootstrap-3-3-2-released/
Tested in local the development mode.
Thanks!
=> Update Bootstrap to version 3.3.2

lib/custom.js, lib/db/file.js, lib/db/mysql.js, lib/db/sql_templates.json, lib/db/sqlite.js, lib/handlers/bin.js, lib/models/user.js, lib/store.js, public/js/chrome/save.js, views/index.html
PR to change the user listings so we get better details about the actual bin content.
- What if there's no HTML?
- What if the HTML is the boilerplate (`title=JS Bin`) and we never see the HTML again? It'll be "JS Bin" repeated over and over...
=> Add API endpoint to get title + desc for users

lib/app.js
Using `set` is not breaking things here though, since it returns the value when a second parameter isn't given.
=> Get instead of set url prefix

public/js/jsbin.js
Deep copy of prefs, rather than shallow. No idea when that changed...
=> Fixed #2260

public/js/editors/libraries.js
- Adds ember data v1.0.0-beta.16 to the list of libraries
- Adds an "Ember" group that contains ember and ember data
Ember data and its [Fixture Adapter](http://emberjs.com/api/data/classes/DS.FixtureAdapter.html) are really useful when making jsbins. It would be nice to not have to go find a link to the build and add the script tag manually.
=> Add Ember Data v1.0.0-beta.16 to libraries

public/js/editors/libraries.js
This PR updates urls of Bootstrap CDNs to latest 3.3.4 version urls.
Please see - to see why they skipped 3.3.3 version:
http://blog.getbootstrap.com/2015/03/16/bootstrap-3-3-4-released/
Tested locally with:
http://jsbin.com/nucada/6/edit
Thanks!
=> Update Bootstrap *latest* library to version 3.3.4

public/js/editors/libraries.js
- Updates the Ember.js library to v1.11.1, which is the current stable version.
- Updates the Ember data library to v1.0.0-beta.16.1.
[Ember Release Builds](http://emberjs.com/builds/#/release)
=> Update Ember library to v1.11.1 and Ember data to v1.0.0-beta.16.1

public/js/editors/libraries.js, public/js/processors/processor.js, views/index.html
It is implemented via compiler as a service at http://himera-emh.herokuapp.com/ since ClojureScript compiler depends on Java. While there was a port of ClojureScript in ClojureScript it is not up to date. I will think about adding Wisp support also in the future, which is a ClojureScript subset in JavaScript.
It works, but error handling is not perfect at the moment and ClojureScript library has to be added as a separate step via the library dropdown list.
We don't get line and column from ClojureScript compiler.
After I get a ClojureScript compile error and then fix it then the error list is spammed with (presumably) JavaScript errors for some reason.
=> Add support for ClojureScript

public/custom/emberjs/default.html, public/js/editors/libraries.js
Thanks for merging the other ones. Sadly they're already out of date :panda_face: 
This updates the ember version to 1.11.3 (latest) and replaces deprecated `{{#each ... in ...}}` syntax in the default ember template.
=> Update ember.js to v1.11.3

config.default.json, lib/routes.js, public/js/chrome/share.js, public/js/jsbin.js
Allows output urls to be output.jsbin.com to harden security around origin attacks. 
Yay. :tada: :man:  :gun: (me)
=> Support security.preview config

public/js/editors/libraries.js
This PR:
- updates Foundation libraries to 5.5.2 version
- adds those libraries that are used in Foundation
*Complete* example download, so user can start with the same
example markup html as in Zurb's documentation
For example one should be able to use generated template to render exactly the same content as provided by Zurb in *Complete* download file:
http://foundation.zurb.com/develop/download.html
http://jsbin.com/debehe/2/edit?html,js,output
Thanks!
=> Update Zurb Foundation to 5.5.2 version

public/js/editors/libraries.js
[In my other pull request](https://github.com/jsbin/jsbin/pull/2368#issuecomment-107027702) I tried to add the ES6/7 shims with Babel, but I think the better way is just adding the [`core-js`](https://github.com/zloirock/core-js) library to the libraries dropdown.
This pull request adds `core-js` to the list of libraries and creates a group called `shims`, which also includes the ES5 shim.
=> add core-js shim to libraries

public/js/editors/libraries.js
- Popcorn.js 1.5.6 (Core)
- Popcorn.js 1.5.6 (Core + Extensions)
=> Adds Popcorn.js 1.5.6 to libraries

public/custom/emberjs/default.html, public/js/editors/libraries.js
- Bumps ember version to 1.12.1 (current release)
- Bumps ember data to 1.0.0-beta.19
=> Bump ember and ember-data versions

lib/fat-flash.js, lib/handlers/bin.js, lib/routes.js, package.json
Since we moved to a separate loader for the bin content, it meant that the 2nd http request (for start.js) didn't know anything about the POSTed values sent to the editor page. I tried to store it originally on the `req.flash` but the example pages from the FT were great because they were larger than the cookie could handle (and thus were chomped and discarded).
It took me a looooong time to work it out, but actually a simple memory store fixes the issue. Similar to a flash that's stored on the cookie, but this is a time sensitive flash that's kept in memory, and removed as soon as it's retrieved (but also removed after a 5 second timeout). Since it's an edge case of JS Bin, I'm happy that it's in memory (though I will have to keep an eye on it too).
Fixes #2425
=> fix: support posting again

public/js/editors/libraries.js
This commit updates used Bootstrap CDN urls to use version 3.3.5:
http://blog.getbootstrap.com/2015/06/15/bootstrap-3-3-5-released/
Thanks!
=> Update Bootstrap version to 3.3.5

package.json
This should be helpful in heading off issues such as #2370 and #2358 and prevent people from heading down the wrong path in troubleshooting. Also corrected the `license` option while I was there: `licenses` was deprecated a while back apparently and without `license` npm logs warnings about a lack of license.
=> Add engine advisory field to package.json

public/js/embed.js
Instead of setting the .src on the iframe causing the url to push onto the history stack.
Fixes #2464
=> fix: embed replaces iframe to avoid history push

lib/db/sqlite.js
The sqlite ID generation code was intending to recursively try longer
IDs until one was found without collision, however the recursive call
didn't actually try longer IDs, and just made 10 attempts at finding a
3 character ID (the default).
This was causing my self-hosted instance of jsbin to fail to create IDs longer than 3 characters, and as we created more and more bins the chance of collision was very high and saving was very difficult.
=> fix: generate longer IDs when using sqlite

public/js/editors/libraries.js
I'll be submitting PRs changing this to further 3.0.0 alphas/betas so that people can test the latest released preview of the upcoming jQueries 3.0.0.
BTW, I've noticed that some of the links direct to minified files and some to full ones (like jQuery UI). Why is that? Wouldn't it be better if all links were non-minified? It's just for testing anyway.
=> Add jQuery & jQuery Compat 3.0.0-alpha1

public/js/editors/libraries.js
Bumps ember-data version to 1.13.6 ([current release](http://emberjs.com/builds/#/release))
=> Bump ember-data version to 1.13.6

public/js/editors/libraries.js
New Three.js library is available (https://cdnjs.com/libraries/three.js)
=> Update three.js from 67 -> 72

public/js/editors/libraries.js
Fixes #2549 - D3.js Library Not Loading on Bins Using Https
The D3 website doesn't serve the D3.js file over https so I've changed it to make use of cdnjs and specified the specific (latest) version.
=> Changed D3.js to use https URL

docs/running-your-own-jsbin.md
Noticed a few GitHub issues where people tried installing with an unsupported Node version.
=> Update docs on installing via npm

docs/session-keys.md, lib/addons/openshift.js, lib/app.js, package.json
After getting frustrated with trying to deploy JSBin in Heroku, I decided to go for OpenShift instead. Modifying the JSBin code to run there proved very simple:
- Fetch options from openshift env vars (if available)
- `grunt build` on postinstall
- Ensure `express` listens only on one network interface
With this, JSBin can just be pushed to a openshift git repo endpoint, and everything will run as expected.
=> Allow running inside OpenShift cloud

public/js/editors/libraries.js
- removes RxJS 2.x links... They're pretty old and people should be using 4.x in production right now.
- updates RxJS-DOM to 7.x ... this is the latest version, and requires RxJS 4.x
- adds link for RxJS 5.0.0-alpha.8 ... RxJS 5 is a total rewrite of RxJS that is meant to be faster and align with the [ES7 Observable Spec](https://github.com/zenparsing/es-observable). As such, the API is quite different, and we'd love for people to be able to play with it in JSBin. It's also used for Angular 2.
Really appreciate the help and the service, @remy and others! 🍻
=> Remove RxJS 2, Add RxJS 5, update RxJS-DOM

views/index.html
This updates the keyboard shortcuts help text for indenting and unindenting to be correct, as reported in #2553
=> Update keyboard shortcuts help text

public/js/editors/libraries.js
This is a trivial commit, just updating CDN links.
The 3.3.6 resources are already available at bootstrapcdn.com:
[https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css](https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css)
[https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js](https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js)
Thanks!
=> :arrow_up: Update Bootstrap to 3.3.6

public/js/processors/processor.js
Part of the future PR sneaked in into #2636
Having this doesn't require to have System.js loaded to work with typescript.
=> Make typescript work without System.js

public/js/processors/processor.js
This PR fixes an error in ClojureScript processor, where it was failing when reading any occurrence of `0` from input string.
=> Fix 'Invalid number format [0]' error in CLJS processor

lib/handlers/bin.js, lib/processors/index.js
For some reason didn't work before
=> Make setting es6/babel as a preprocessor work when pre-populating bins with POST request

docs/running-your-own-jsbin.md
`gurantee` → `guarantee`
`concatted` → `concatenated`
=> docs: fix typos

public/custom/react/default.html, public/js/editors/libraries.js
Facebook's CDN was failing for React 0.14.3. Updating to the latest 0.14.x seemed to fix it. Multiple incidents like this have been reported to me at [my page](http://reactfordesigners.com/labs/reactjs-introduction-for-people-who-know-just-enough-jquery-to-get-by/):
https://twitter.com/chibicode/status/706187916670701569
=> React 0.14.7

public/js/editors/libraries.js
1. Add the new jQuery 2.2.3/1.12.3
2. Drop jQuery Compat as we've decided to not release it at all, there's only been one alpha and this version is now abandoned, the WIP URL is redirecting to the main one.
3. Add jQuery 1.10.2 & 2.0.3, they were missing for some reason.
=> Add missing jQueries, drop jQuery Compat

public/js/editors/libraries.js
Current jsbin version is 3.0.1. 3.0.1 docs are no longer listed on the lodash website. You have to go to the tagged source on github.
This example of `_.has` taken from the lodash docs for the latest version returns `false` instead of `true`. (3.0.1 does not support nested object checks).
```
_.has({ 'a': { 'b': { 'c': 3 } } }, 'a.b.c');
```
=> upgrade lodash to 4.5.1

lib/handlers/session.js, public/js/login.js
This pull request addresses two minor details related to the password reset mechanism.
1. Requesting a password reset results in the email address associated with the account being output in the success notification. There is the potential for misuse, allowing the email address associated with a JS Bin account to be obtained by knowing only the username. This PR genericises the success notification and removes the email from the output.
2. Requesting a password reset without entering an email address or username results in a validation error. The text refers to the email/username input being above the message. This PR corrects this, as the input field is below the validation message.
=> Password reset message improvements (incl. email address leakage)

lib/routes.js
Otherwise it would be 'text/html', which is wrong.
=> Set correct content type for /bin/user.js

public/js/editors/libraries.js
**lodash fp** is the functional variant of **lodash** library similar to **Ramda** library
:point_right: **https://github.com/lodash/lodash/wiki/FP-Guide**
Grouped as "Lodash"
:white_check_mark: Locally tested 
:loop: Using [**jsDelivr**](http://www.jsdelivr.com/?query=lodash) as CDN
&nbsp;
> **NOTE 1:** Added lodash 3.x as many companies still use lodash 3.x and have not yet upgraded to lodash 4.x (_due to breaking changes_)
&nbsp;
> **NOTE 2:** Lodash FP is basically combination of [lodash main ](https://cdn.jsdelivr.net/lodash/4/lodash.min.js) with [lodash fp](https://cdn.jsdelivr.net/lodash/4/lodash.fp.min.js). I've used a grouped CDN url so that only a single script tag is used for adding lodash fp.
If needed, I can separate it to add two script tags i.e.
> ```html
<script …
```
=> feat(Library): Add lodash fp and update lodash

public/js/processors/processor.js
This PR fixes ClojureScript processor output logging in "Output" pane by escaping output string.
=> Fix ClojureScript processor output logging

lib/features.js, test/unit/features.test.js
Specifically for training companies that support jsbin
=> feat: allow whitelisted referrers in embeds

public/js/editors/libraries.js
Some projects still use Vue 1, but version 2 was recently released 😄
=> fix: Add Vue JS 2.0.3 library

public/js/editors/libraries.js
- sap_belize is the new default for OpenUI5 since version 1.40
- the URL is our CDN (Content Delivery Network)
- switched order of description
I am from the UI5 team, in case of questions please contact me at mi.graf@sap.com, thank you!
=> Updated OpenUI5 library entry to latest theme

public/js/editors/libraries.js
=> Library - Update RxJs 5.0.0-beta to 5.0.3 final

public/js/render/console.js
Matched chrome's assertions:
Original:
After fix:
=> Fix for #2833, console.assert wrong output

public/js/editors/libraries.js
This prevents the link being mistaken for JavaScript file rather than a CSS file.
Both:
https://unpkg.com/blaze
and
https://unpkg.com/blaze/dist/blaze.min.css
Resolve to the same thing but the editor thinks the first URL is a script URL
=> Update Blaze CDN link

public/css/mobile.css
Right now, the ethical ads bar floats in front of the editor
This prevents users from being able to see the last lines of their code
With `calc` in css (notice you can see the bottom of the scroll bars
43 px because
* .ea-placement has `10px` + `12px` padding on top/bottom
* .ea-text has a size of `14px` plus a 1.5 line height (`7px`)
* 10 + 12 + 14 + 7 = 43
=> Preventing main container from wrapping under ea banner
